version: '3'
services:
  mongoM1:
    image: mongo
    container_name: mongoM1
    hostname: mongoM1
    ports:
      - 27017:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongoM2:
    image: mongo
    container_name: mongoM1
    hostname: mongoM1

    ports:
      - 27018:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongoM3:
    image: mongo
    container_name: mongoM1
    hostname: mongoM1

    ports:
      - 27019:27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]



